---
title: "Formative"
author: "Zehao Qian"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 0: Prepare for the Runtime and Dataset

gridExtra is a good library for combining multiple ggplots graphs in one graph, while par() can't make it.

```{r warning=FALSE,message=FALSE}
# --------------------------------------------------------
## clear the environment var area
# rm(list = ls())
## clear all plots
# graphics.off()
## clear the console area
# cat("\014")
# --------------------------------------------------------
# install.packages("gridExtra")
# --------------------------------------------------------
require(lme4)
require(lmerTest)
require(ggplot2)
require(sjPlot)
require(gridExtra)
```

Download data set from GitHub and show the first lines.

```{r}
CRT <- read.csv("https://andygolightly.github.io/teaching/MATH43515/CRT.csv", header=TRUE)
head(CRT)
# dim(CRT)
```

------------------------------------------------------------------------

## Part 1: Introduction

-   randomized controlled trials and cluster randomized trials
-   Intro to the CRT data set
    -   `Pupil`: anonymized student ID;

    -   `School`: anonymized school ID $\{1,\dots,20\}$;

    -   `Class`: anonymized class ID $\{1,2\}$;

    -   `Intervention`: Intervention indicator (0=control; 1=treatment);

    -   `FSM`: pupil eligible for free school meal (0=not eligible; 1 =eligible)

    -   `Pretest`: A pre-test score for each pupil;

    -   `Posttest`: A post-test score for each pupil (**response**).
-   Histograms / Bar Plots / EDA with ggplots
-   Check missing values
-   Target: predict the Post-test

```{r}
summary(CRT)
```

```{r}
# --------------------------------------------------------
bar.Posttest = ggplot(data = CRT, aes(Posttest)) +
  geom_bar()
bar.Pretest = ggplot(data = CRT, aes(Pretest)) +
  geom_bar()
bar.Intervention = ggplot(data = CRT, aes(Intervention)) +
  geom_bar()
bar.School = ggplot(data = CRT, aes(School)) +
  geom_bar()
bar.FSM = ggplot(data = CRT, aes(FSM)) +
  geom_bar()
bar.class = ggplot(data = CRT, aes(class)) +
  geom_bar()
# --------------------------------------------------------
# boxplot
boxplot.Posttest = ggplot(data = CRT, aes(Posttest)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 1)
boxplot.Pretest = ggplot(data = CRT, aes(Pretest)) +
  geom_boxplot(outlier.colour = "red", outlier.shape = 1)
# --------------------------------------------------------
# put these bar charts together
grid.arrange(bar.Posttest,
             bar.Pretest,
             bar.Intervention,
             bar.School,
             bar.FSM,
             bar.class,
             ncol = 3)
grid.arrange(boxplot.Posttest,
             boxplot.Pretest,
             ncol = 2)
# --------------------------------------------------------
# remove the plot cache memory
remove(bar.Posttest)
remove(bar.Pretest)
remove(bar.Intervention)
remove(bar.School)
remove(bar.FSM)
remove(bar.class)
remove(boxplot.Posttest)
remove(boxplot.Pretest)
```

```{r message=FALSE}
# Correlation between 
library("GGally")
ggpairs(CRT)+theme_bw()
```

```{r}
## Not good to read and analyse
# tapply(CRT$School, CRT$class, table)
```

## Part 2: Methods

## Part 3: Analysis

```{r}
# empty model / intercept-only model
Model.0 = lmer(Posttest ~ 1 + (1 | School)
                  + (1 | School:class),
                  data = CRT)
# summary(Model.0)
# --------------------------------------------------------
# REsummary <- as.data.frame(VarCorr(Model.0))
# REsummary
# summary(Model.0)$varcor
# --------------------------------------------------------
Model.1 = lmer(Posttest ~ Pretest + (1 | School)
                  + (1 | School:class),
                  data = CRT)
# summary(Model.1)
# --------------------------------------------------------
ranova(Model.0)
ranova(Model.1)
anova(Model.1, Model.0)
```

```{r}
Model.2 = lmer(Posttest ~ Pretest + (Pretest | School)
                  + (1 | School:class),
                  data = CRT)
ranova(Model.2)
anova(Model.2, Model.1)
```

```{r}
Model.3 = lmer(Posttest ~ Pretest + (1 | School)
               + (Pretest | School:class),
               data = CRT)
ranova(Model.3)
anova(Model.3, Model.1)
```

```{r}
Model.4 = lmer(Posttest ~ Pretest + FSM + (FSM | School)
               + (1 | School:class),
               data = CRT)
ranova(Model.4)
anova(Model.4, Model.1)
```

```{r}
Model.5 = lmer(Posttest ~ Pretest + Intervention + (1 | School)
               + (1 | School:class),
               data = CRT)
ranova(Model.5)
anova(Model.5, Model.1)
```

```{r}
Model.6 = lmer(Posttest ~ Pretest + Intervention + (1 | School)
               + (Intervention | School:class),
               data = CRT)
ranova(Model.6)
anova(Model.6, Model.5)
```

```{r}
Model.7 = lmer(Posttest ~ Pretest + Intervention + (Intervention | School)
               + (1 | School:class),
               data = CRT)
ranova(Model.7)
anova(Model.7, Model.5)
```

```{r}
require(performance)
# https://easystats.github.io/performance/reference/icc.html
icc(Model.0)
icc(Model.1)
icc(Model.2)
icc(Model.3)
icc(Model.4)
icc(Model.5)
icc(Model.6)
icc(Model.7)

```

## Part 4: Discussion of results

------------------------------------------------------------------------

## References

[Evaluating Intervention Programs with a Pretest-Posttest Design: A Structural Equation Modeling Approach](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5332425/pdf/fpsyg-08-00223.pdf)

## Word count

```{r message=FALSE, warning=FALSE}
# install.packages("devtools")
# devtools::install_github("benmarwick/wordcountaddin",
#                          type = "source", dependencies = TRUE)
require(wordcountaddin)
word_count()
text_stats()
```
